name: issueテンプレート
description: issueテンプレート
labels: "運用"
projects: "ysk91/3"
body:
  - type: markdown
    attributes:
      value: |
        チケット作成にご協力いただきありがとうございます！
        右側のlabelsから該当のものを選択してください。
        issue作成後はProjectからstatusを選択してください。
  - type: textarea
    id: require
    attributes:
      label: 要件
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: conversation
    attributes:
      label: 会話履歴
      description: Slack等の会話履歴を記入してください
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        # これ以降はチケット作成後に記載する内容です
  - type: checkboxes
    id: schedules
    attributes:
      label: スケジュール
      description: 進捗確認用
      options:
        - label: 要件
          required: false
        - label: 要件fix
          required: false
        - label: 開発
          required: false
        - label: テストレビュー
          required: false
        - label: QA
          required: false
        - label: UAT
          required: false
        - label: リリース
          required: false
        - label: 先方連絡
          required: false
  - type: textarea
    id: qa
    attributes:
      label: QA
      value: テスト仕様書のリンクを貼って下さい
    validations:
      required: false
  - type: textarea
    id: man-hours
    attributes:
      label: 工数
      value: |
        - PM
        - エンジニア
        - QA
    validations:
      required: false
