name: Hello
on:
  pull_request:
    types: [opened, reopened]
    paths: ['**.py']
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run flake8
        id: flake8
        run: flake8 .
      - name: Comment
        run: |
          gh pr comment "${GITHUB_HEAD_REF}" -b "Hello, ${GITHUB_ACTOR}!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
