name: Hello
on:
  pull_request:
    types: [opened, reopened]
jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - run: gh pr comment "${GITHUB_HEAD_REF}" -b "Hello, ${GITHUB_ACTOR}!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
