name: Link to Project
on:
  issues:
    types: [opened]
defaults:
  run:
    shell: bash
jobs:
  manage_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Link Issue to GitHub Project
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PROJECT_ID: PVT_kwHOBlW0YM4AqOrn # ここに既存のプロジェクトIDを入力
          STATUS_FIELD_ID: PVTSSF_lAHOBlW0YM4AqOrnzghgpf0 # ここにステータスフィールドIDを入力
        run: |
          issue_number=${{ github.event.issue.number }}

          # アイテムをプロジェクトに追加
          result=$(gh api graphql -f query='
          mutation($projectId: ID!, $issueId: ID!) {
            addProjectV2ItemById(input: {projectId: $projectId, contentId: $issueId}) {
              item {
                id
              }
            }
          }' -f projectId=$PROJECT_ID -f issueId="gid://github.com/Issue/${issue_number}" --jq '.data.addProjectV2ItemById.item.id')

          # ステータスをTo Doに設定
          gh api graphql -f query='
          mutation($itemId: ID!, $fieldId: ID!, $value: String!) {
            updateProjectV2ItemFieldValue(input: {projectId: $projectId, itemId: $itemId, fieldId: $fieldId, value: $value}) {
              projectV2Item {
                id
              }
            }
          }' -f projectId=$PROJECT_ID -f itemId="$result" -f fieldId=$STATUS_FIELD_ID -f value="To Do" --header "Authorization: bearer $GITHUB_TOKEN"

      - name: Comment for Requirement
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=${{ github.event.issue.number }}
          gh issue comment $issue_number --body "## 要件\n\n### 資料"
      - name: Comment for Engineering
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=${{ github.event.issue.number }}
          gh issue comment $issue_number --body "## 実装\n\n### 実装前メモ"
      - name: Comment for QA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          issue_number=${{ github.event.issue.number }}
          gh issue comment $issue_number --body "## QA\n\n### テスト仕様書"
