name: Manual
on:
  workflow_dispatch:
    inputs:
      greeting:
        type: string
        default: Hello
        required: true
        description: A cheerful word
      label:
        type: choice
        options:
          - bug
          - feature
          - enhancement
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ inputs.greeting }}"
      - run: echo "${{ inputs.label }}"
